### PR TITLE
Added neovim support.

### PR DESCRIPTION
**Pull request by RianFuro**
Added an algorithm to consider neovims different command set. Added test cases to reflect neovim features and the absence of neovim features for regular vim parsing. Added a toggle option as an argument that defaults to regular vim if not specified.

The changes are designed in a way so the default behavior is not changed. Using the toggle should be completely optional.

After I was done i realized that the javascript part looks like it's created automatically, but oh well :D

### CODE REVIEW

**Comment by ynkdir** [comment]
Thank you.

 js/vimlparser.js  and py/vimlparser.py should not be edited by hand because it is generated file.  You can generate them with `:so js/jscompiler.vim` and `:so py/pycompiler.vim`.  Could you fix it?

**Comment by RianFuro** [comment]
Aaah, that's how it works :) The parser doesn't do the optional --neovim cli parameter though; anyway to fix that? I couldn't find where the entry point is generated :/

**Comment by ynkdir** [comment]
>  I couldn't find where the entry point is generated

That is in  js/vimlfunc.js and py/vimlfunc.py.

**Comment by RianFuro** [comment]
Thanks! :) Anything else?

**Comment by ynkdir** [comment]
It's complete.  Thanks!

**Pull request merged**
